Update Jenkinsfile

diff --git a/continuous-deployment/Jenkinsfile b/continuous-deployment/Jenkinsfile
--- a/continuous-deployment/Jenkinsfile
+++ b/continuous-deployment/Jenkinsfile
@@ -1,5 +1,8 @@
 pipeline {
     agent any
+    options {
+        timeout(time: 10, unit: 'MINUTES')
+    }
 
     parameters {
         choice(name: 'DEPLOYMENT_ACTION', choices: ['', 'Monolithic_Deployment', 'Microservice_Deployment', 'All_Deployments'], description: 'Select Your Preffered Deployment Type')
@@ -49,6 +52,9 @@ pipeline {
         }   
 
         stage('Deploy To Microservice Server') {
+            when {
+                expression { params.DEPLOYMENT_ACTION == "All_Deployments" || params.DEPLOYMENT_ACTION == "Microservice_Deployment" }
+            }
             steps {
                 script {
                    def deployCommand = '''
@@ -100,42 +106,72 @@ services:
         }
 
         stage('Deploy To Monolithic Server') {
+            when {
+                expression { params.DEPLOYMENT_ACTION == "All_Deployments" || params.DEPLOYMENT_ACTION == "Monolithic_Deployment" }
+            }
             steps {
                 script {
                    def Command = '''
-                       set -ex
-                       cd ~/blog-app/
-                # Check if any process is listening on port 8081 and kill it
-                PID=$(/usr/sbin/lsof -t -i:8081)
-                if [ -n "$PID" ]; then
-                    kill $PID || true
-                    echo "Killed process $PID"
-                else
-                    echo "No process found listening on port 8081"
-                fi
-                 # Export Variables To Retrieve Secrets from Secrets Manager
-                export ARN="${SECRETS_ARN}"
-                secret=$(aws secretsmanager get-secret-value --secret-id $ARN --query "SecretString" --output=text)
-                export NEXUS_USERNAME=$(echo $secret | sed -n "s|.*\\\"NEXUS_USERNAME\\\":\\\"\\([^\\\"]*\\)\\\".*|\\1|p")
-                export NEXUS_PASSWORD=$(echo $secret | sed -n "s|.*\\\"NEXUS_PASSWORD\\\":\\\"\\([^\\\"]*\\)\\\".*|\\1|p")
-                
-                # Download And Run Desired Jar file
-                curl -u "${NEXUS_USERNAME}":"${NEXUS_PASSWORD}" -O "${NEXU_JAR_FILE_URL}"
-                java -jar "${JAR_FILE_NAME}" > logfile 2>&1 &
-                echo "Started new blog application"
-                sleep 7
-                cat logfile
-            '''
+                    set -ex
+                    
+                    mkdir -p /home/${REMOTE_USER}/blog-app
+                    
+                    cd ~/blog-app/
+                    
+                    echo '#!/bin/bash
+                    # Check if any process is listening on port 8081 and kill it
+                    PID=$(/usr/sbin/lsof -t -i:8081)
+                    if [ -n "$PID" ]; then
+                        kill $PID || true
+                        echo "Killed process $PID"
+                    else
+                        echo "No process found listening on port 8081"
+                    fi
+                    
+                    # Export Variables To Retrieve Secrets from Secrets Manager
+                    export ARN="${SECRETS_ARN}"
+                    secret=$(aws secretsmanager get-secret-value --secret-id "${ARN}" --query "SecretString" --output=text)
+                    
+                    if [ $? -ne 0 ]; then
+                        echo "Failed to retrieve secrets"
+                        exit 1
+                    fi
+                    export NEXUS_USER=$(echo $secret | sed -n "s|.*\\\"NEXUS_USERNAME\\\":\\\"\\([^\\\"]*\\)\\\".*|\\1|p")
+                    export NEXUS_PASS=$(echo $secret | sed -n "s|.*\\\"NEXUS_PASSWORD\\\":\\\"\\([^\\\"]*\\)\\\".*|\\1|p")
+                    
+                    # Download And Run Desired Jar file
+                    curl -u "${NEXUS_USER}":"${NEXUS_PASS}" -O "${NEXUS_JAR_FILE_URL}"
+                    if [ $? -ne 0 ]; then
+                        echo "Failed to download JAR file"
+                        exit 1
+                    fi' > deployment.sh
+                    
+                    chmod +x deployment.sh
+                    
+                    cat deployment.sh
+                    
+                    ./deployment.sh
+                    
+                    java -jar "${JAR_FILE_NAME}" > logfile 2>&1 &
+                    if [ $? -ne 0 ]; then
+                        echo "Failed to start the application"
+                        cat logfile
+                        exit 1
+                    fi
+                    echo "Started new blog application"
+                    sleep 7
+                    cat logfile
+                    '''
 
             sshPublisher(publishers: [sshPublisherDesc(
                 configName: env.MONOLITHIC_SERVER,
                 transfers: [sshTransfer(
-                    sourceFiles: 'target/blog-0.0.1-SNAPSHOT.jar',
-                    removePrefix: 'target/',
                     makeEmptyDirs: false,
-                    remoteDirectory: '/blog-app/',
+                    remoteDirectory: '',
                     execCommand: Command,
-                    execTimeout: 120000
+                    execTimeout: 120000,
+                    removePrefix: '',
+                    sourceFiles: ''
                 )],
                 usePromotionTimestamp: false,
                 useWorkspaceInPromotion: false,
